![imagen](./img/ejercicios.png)

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [ ]:
import numpy as np
my_array = np.arange(10)
print(my_array)

arr_impar = my_array % 2 == 1
print(my_array[arr_impar])
print(np.flip(my_array[arr_impar]))

## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [ ]:
print(my_array[8:6:-1])

## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [ ]:
print(my_array[2::-1])

## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [ ]:
arr = np.arange(1,21)
a = np.reshape(arr,(4,5))
print(a)

In [ ]:
print(np.flip(a))

## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [ ]:
print(a[:2, :2]) #las dos primeras filas y columnas

## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [ ]:
print(a[::2,::2])

## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [ ]:
b = a[:3,::]
print(b[::,::-1])

## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [ ]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

loro_array = np.array(x == 'Loro')
print('array de loros booleanos:', loro_array)
print('loros:', x[loro_array])

In [ ]:
print([x[0], x[-2]])

## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [ ]:
ejer_9 = np.arange(20)
np.reshape(ejer_9,(2,5,2))

## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [ ]:
print(np.flip(a))

## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [ ]:
ceros_array = np.zeros(10)
print(ceros_array)
print(ceros_array.itemsize)
print(ceros_array.nbytes)

ceros_array[3] = 1

print(ceros_array)

## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [ ]:
ejer_12 = np.arange(10,50)
print(ejer_12)

print(np.flip(ejer_12))

## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [ ]:
ejer_13 = [1,2,0,0,4,0]

print(np.nonzero(ejer_13))

## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [ ]:
np.random.seed(1234)
ejer_14 = np.random.randint(100, size=(10,10))
print(ejer_14)
print('max:' , np.max(ejer_14))
print('min:' , np.min(ejer_14))

## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [ ]:
np.random.seed(5678)
ejer_15 = np.random.rand(30)
print(ejer_15)
print('media', np.mean(ejer_15))

## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quiras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [ ]:
arr= np.ones((10, 10))
arr[1:-1,1:-1] = 0

print(arr)

## Ejercicio 17
Crea una mtriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [ ]:
ejer_17 = [[1,0], 
           [0,1]] 
print(ejer_17)

print(np.tile(ejer_17,(4,4)))

## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [ ]:
ejer_18 = [[1,0], 
           [0,1]] 

print(np.tile(ejer_18,(4,4)))

## Ejercicio 19
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [ ]:
np.random.seed(0000)
ejer_19 = np.random.randint(1,20, size=(5,5))
print(ejer_19)
print((ejer_19 - np.mean(ejer_19)) / np.std(ejer_19))

## Ejercicio 20
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [ ]:
ejer = np.arange(11)
print('1:', ejer)
ejer_2 = ejer[:].copy()
ejer_2[4:8] = -1
print('2:', ejer_2)
ejer_20_3 = np.where(ejer_2 == -1, ejer * ejer_2, ejer)
print('3:', ejer_20_3)

## Ejercicio 21
#### Bonus track. Mini hundir la flota
1. Crea un tablero de 10x10 relleno del carácter espacio ( ).
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**

**TIP apartado 5**: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones [(5,0), (5,1), (5,2), (5,3)]. Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. **Ojo con las posiciones donde ya hay barco!!!**

Usa `import random` para elegir las coordenadas aleatorias.

In [ ]:
import numpy as np

tablero = np.full((11,11), fill_value=' ')
indice = -1
for i in range(len(tablero)):
    tablero[0][0] = ' '
    indice += 1
    tablero[0][i] = indice
    tablero[i][0] = indice
    
print(tablero)

In [ ]:
tablero[(2,1),(1,1)] = 'O'
print(tablero)

In [ ]:
tablero[(1,3)] = 'O'
tablero[(1,4)] = 'O'
tablero[(1,5)] = 'O'
tablero[(1,6)] = 'O'
print(tablero)

In [ ]:
tablero[(1,3)] = 'X'
print(tablero)

In [ ]:
tablero[(8,7)] = '-'
print(tablero)

In [ ]:

def barco():
    """
    Coloca un barco de tamaño cuatro, con una orientación (N,S,E,O) 
    de manera aleatoria dentro del tablero.
    
    """  
    cant_ship = 1  # Número total de barcos
    rows, columns = tablero.shape
        
    barcos = []
        
    while cant_ship > 0:
        ship = 4  
        row = np.random.randint(1, 11)
        column = np.random.randint(1, 11)
        position = np.random.choice(['norte', 'sur', 'este', 'oeste'])

        if position == 'norte' and all(tablero[row:row-ship:-1,column] != 'X'):    
            if row - ship > 0 and row + ship <= rows: # Norte/sur movimiento vertical       
                tablero[row:row-ship:-1,column] = 'X' 
                cant_ship = cant_ship - 1
                barco_info = {
                    'barco': ship,
                    'fila': row,
                    'columna': column,
                    'dirección': position
                }
                barcos.append(barco_info)
                
        elif position == 'sur' and all(tablero[row:row+ship,column] != 'X'): #Comprueba que las casillas siguientes no contengan 'X'           
            if row - ship > 0 and row + ship <= rows: 
                tablero[row:row+ship,column] = 'X' 
                cant_ship = cant_ship - 1
                barco_info = {
                    'barco': ship,
                    'fila': row,
                    'columna': column,
                    'dirección': position
                }
                barcos.append(barco_info)
        
        elif position == 'oeste' and all(tablero[row,column:column-ship:-1] != 'X'):              
            if column - ship > 0 and column + ship <= columns:       
                tablero[row,column:column-ship:-1] = 'X' 
                cant_ship = cant_ship - 1
                barco_info = {
                    'barco': ship,
                    'fila': row,
                    'columna': column,
                    'dirección': position
                }
                barcos.append(barco_info)
            
        elif position == 'este' and all(tablero[row,column:column+ship] != 'X'):   
            if column - ship > 0 and column + ship <= columns:
                tablero[row,column:column+ship] = 'X' 
                cant_ship = cant_ship - 1
                barco_info = {
                    'barco': ship,
                    'fila': row,
                    'columna': column,
                    'dirección': position
                }
                barcos.append(barco_info)
        else:
            # mensaje = 'No se pudo agregar el barco'
            # barcos.append(mensaje)
            cant_ship = cant_ship
                
    # Imprimir el tablero
    print(tablero)
    
    # Imprimir la información de los barcos
    print("Información de los barcos:")
    for index, barco_info in enumerate(barcos):
        print(f"Barco {index + 1}: {barco_info}")
    

In [ ]:
barco()